export const med_wiki=[
    // Cardiovascular
    {
        name: "Aspirin",
        description: "Aspirin is a medication used to reduce pain, fever, and inflammation.",
        usage: "It is often used to prevent heart attacks, strokes, and blood clot formation.",
        side_effects: "Common side effects include gastrointestinal bleeding and heartburn.",
        precautions: "Do not take aspirin if you are allergic to it. Avoid using aspirin during pregnancy.",
        categories: ["Cardiovascular", "Pain Killers"],
    },
    {
        name: "Atenolol",
        description: "Atenolol is a beta-blocker medication used to treat high blood pressure and heart-related chest pain.",
        usage: "It works by blocking the effects of certain natural chemicals in the body, such as adrenaline.",
        side_effects: "Side effects may include feeling tired, dizziness, or a slow heart rate.",
        precautions: "Do not stop taking atenolol suddenly without consulting your doctor.",
        categories: ["Cardiovascular"],
    },
    {
        name: "Lisinopril",
        description: "Lisinopril is an ACE inhibitor medication used to treat high blood pressure, heart failure, and to improve survival after heart attacks.",
        usage: "It works by relaxing blood vessels, making it easier for the heart to pump blood.",
        side_effects: "Common side effects include dizziness, cough, and headache.",
        precautions: "Avoid alcohol while taking lisinopril, as it can further lower blood pressure.",
        categories: ["Cardiovascular"],
    },
    {
        name: "Simvastatin",
        description: "Simvastatin is a statin medication used to lower cholesterol levels and reduce the risk of cardiovascular disease.",
        usage: "It works by inhibiting an enzyme in the liver that plays a key role in cholesterol production.",
        side_effects: "Common side effects include muscle pain, nausea, and constipation.",
        precautions: "Tell your doctor if you have liver disease or a history of kidney problems.",
        categories: ["Cardiovascular"],
    },
    {
        name: "Warfarin",
        description: "Warfarin is an anticoagulant medication used to prevent blood clots from forming or growing larger.",
        usage: "It is commonly used to treat or prevent deep vein thrombosis and pulmonary embolism.",
        side_effects: "Side effects may include bleeding, bruising, or skin necrosis if the dose is too high.",
        precautions: "It is important to have regular blood tests while taking warfarin to monitor its effects.",
        categories: ["Cardiovascular"],
    },

    // Urology
    {
        name: "Tamsulosin",
        description: "Tamsulosin is an alpha-blocker medication used to treat symptoms of an enlarged prostate (benign prostatic hyperplasia, or BPH).",
        usage: "It works by relaxing muscles in the prostate and bladder neck, making it easier to urinate.",
        side_effects: "Common side effects include dizziness, headache, and a stuffy or runny nose.",
        precautions: "Take tamsulosin 30 minutes after the same meal each day to maintain consistent blood levels.",
        categories: ["Urology"],
    },
    {
        name: "Finasteride",
        description: "Finasteride is a medication used to treat male pattern hair loss and benign prostatic hyperplasia (BPH) in men.",
        usage: "It works by blocking the conversion of testosterone to dihydrotestosterone (DHT), which is involved in the development of BPH and hair loss.",
        side_effects: "Common side effects include decreased libido, erectile dysfunction, and breast tenderness.",
        precautions: "Women who are or may become pregnant should not handle finasteride tablets.",
        categories: ["Urology"],
    },
    {
        name: "Oxybutynin",
        description: "Oxybutynin is an anticholinergic medication used to treat overactive bladder and urinary incontinence.",
        usage: "It works by relaxing the bladder muscles and reducing the urge to urinate.",
        side_effects: "Common side effects include dry mouth, constipation, and blurred vision.",
        precautions: "Avoid activities that require mental alertness, such as driving, until you know how oxybutynin affects you.",
        categories: ["Urology"],
    },
    {
        name: "Doxazosin",
        description: "Doxazosin is an alpha-blocker medication used to treat high blood pressure and urinary symptoms associated with benign prostatic hyperplasia (BPH).",
        usage: "It works by relaxing blood vessels and muscles in the prostate and bladder neck, making it easier to urinate.",
        side_effects: "Common side effects include dizziness, headache, and fatigue.",
        precautions: "Take doxazosin at bedtime to minimize the risk of fainting or dizziness.",
        categories: ["Urology"],
    },
    {
        name: "Nitrofurantoin",
        description: "Nitrofurantoin is an antibiotic medication used to treat urinary tract infections (UTIs) caused by bacteria.",
        usage: "It works by stopping the growth of bacteria in the urinary tract.",
        side_effects: "Common side effects include nausea, vomiting, and diarrhea.",
        precautions: "Take nitrofurantoin with food to reduce the risk of stomach upset.",
        categories: ["Urology"],
    },

    // Dermatology
    {
        name: "Hydrocortisone",
        description: "Hydrocortisone is a topical steroid medication used to reduce inflammation and itching associated with skin conditions such as eczema, dermatitis, and insect bites.",
        usage: "Apply a thin layer of hydrocortisone cream to the affected area and gently rub it in.",
        side_effects: "Side effects may include burning, stinging, or redness at the application site.",
        precautions: "Do not apply hydrocortisone cream to broken or infected skin without consulting your doctor.",
        categories: ["Dermatology"],
    },
    {
        name: "Clotrimazole",
        description: "Clotrimazole is an antifungal medication used to treat fungal skin infections such as athlete's foot, ringworm, and jock itch.",
        usage: "Apply clotrimazole cream or powder to the affected area and surrounding skin.",
        side_effects: "Common side effects include itching, burning, or irritation at the application site.",
        precautions: "Avoid contact with eyes, nose, mouth, and other mucous membranes while using clotrimazole.",
        categories: ["Dermatology"],
    },
    {
        name: "Benzoyl Peroxide",
        description: "Benzoyl peroxide is a topical medication used to treat acne by killing acne-causing bacteria and reducing inflammation.",
        usage: "Apply a thin layer of benzoyl peroxide gel or cream to clean, dry skin once or twice daily.",
        side_effects: "Side effects may include dryness, peeling, or redness of the skin.",
        precautions: "Avoid excessive exposure to sunlight or artificial UV rays while using benzoyl peroxide.",
        categories: ["Dermatology"],
    },
    {
        name: "Salicylic Acid",
        description: "Salicylic acid is a topical medication used to treat acne, psoriasis, and other skin conditions by promoting the shedding of dead skin cells.",
        usage: "Apply salicylic acid solution or gel to the affected area and gently massage it into the skin.",
        side_effects: "Common side effects include skin irritation, burning, or stinging.",
        precautions: "Avoid using salicylic acid on broken, irritated, or sunburned skin.",
        categories: ["Dermatology"],
    },
    {
        name: "Clobetasol",
        description: "Clobetasol is a potent topical steroid medication used to treat severe inflammatory skin conditions such as eczema, psoriasis, and allergic reactions.",
        usage: "Apply a thin layer of clobetasol cream or ointment to the affected area and gently rub it in.",
        side_effects: "Side effects may include skin thinning, burning, or itching.",
        precautions: "Limit the use of clobetasol to the smallest area and shortest duration necessary to control symptoms.",
        categories: ["Dermatology"],
    },

    // ENT
    {
        name: "Antihistamines",
        description: "Antihistamines are medications used to treat allergy symptoms such as sneezing, itching, and runny nose by blocking the action of histamine in the body.",
        usage: "Take antihistamine tablets or capsules orally, or use antihistamine nasal sprays or eye drops as directed.",
        side_effects: "Common side effects include drowsiness, dry mouth, and blurred vision.",
        precautions: "Avoid alcohol and sedatives while taking antihistamines, as they can increase drowsiness.",
        categories: ["ENT"],
    },
    {
        name: "Decongestants",
        description: "Decongestants are medications used to relieve nasal congestion and sinus pressure caused by allergies, colds, or sinusitis by constricting blood vessels in the nasal passages.",
        usage: "Take decongestant tablets or capsules orally, or use decongestant nasal sprays or drops as directed.",
        side_effects: "Side effects may include increased heart rate, elevated blood pressure, and nervousness.",
        precautions: "Limit the use of decongestants to short-term relief of symptoms, as long-term use can lead to rebound congestion.",
        categories: ["ENT"],
    },
    {
        name: "Nasal Corticosteroids",
        description: "Nasal corticosteroids are medications used to reduce inflammation and relieve nasal congestion, sneezing, and runny nose caused by allergies or nasal polyps.",
        usage: "Use nasal corticosteroid sprays by spraying into each nostril as directed, usually once or twice daily.",
        side_effects: "Common side effects include nasal irritation, nosebleeds, and headache.",
        precautions: "Use nasal corticosteroids regularly for best results, even if symptoms improve.",
        categories: ["ENT"],
    },
    {
        name: "Antibiotics",
        description: "Antibiotics are medications used to treat bacterial infections such as sinusitis, strep throat, and ear infections by killing or inhibiting the growth of bacteria.",
        usage: "Take antibiotics orally as prescribed, or use antibiotic ear drops or eye drops as directed.",
        side_effects: "Side effects may include diarrhea, nausea, and allergic reactions.",
        precautions: "Take antibiotics exactly as prescribed and complete the full course of treatment, even if symptoms improve.",
        categories: ["ENT", "Antibiotics"],
    },
    {
        name: "Steroid Nasal Sprays",
        description: "Steroid nasal sprays are medications used to reduce inflammation and relieve nasal congestion, sneezing, and runny nose caused by allergies or nasal polyps.",
        usage: "Use steroid nasal sprays by spraying into each nostril as directed, usually once or twice daily.",
        side_effects: "Common side effects include nasal irritation, nosebleeds, and headache.",
        precautions: "Use steroid nasal sprays regularly for best results, even if symptoms improve.",
        categories: ["ENT"],
    },

    // Gastrointestinal
    {
        name: "Omeprazole",
        description: "Omeprazole is a proton pump inhibitor medication used to treat acid reflux, ulcers, and gastroesophageal reflux disease (GERD) by reducing the production of stomach acid.",
        usage: "Take omeprazole capsules orally with or without food, usually once daily in the morning.",
        side_effects: "Common side effects include headache, diarrhea, and abdominal pain.",
        precautions: "Do not crush or chew omeprazole capsules, as it may affect their release mechanism.",
        categories: ["Gastrointestinal"],
    },
    {
        name: "Loperamide",
        description: "Loperamide is an antidiarrheal medication used to treat acute diarrhea and chronic diarrhea associated with inflammatory bowel disease (IBD) or irritable bowel syndrome (IBS).",
        usage: "Take loperamide capsules orally with water as directed, usually after each loose stool.",
        side_effects: "Side effects may include constipation, dizziness, and stomach pain.",
        precautions: "Do not exceed the recommended dose or use loperamide for longer than 2 days for acute diarrhea or 10 days for chronic diarrhea without consulting your doctor.",
        categories: ["Gastrointestinal"],
    },
    {
        name: "Metoclopramide",
        description: "Metoclopramide is a prokinetic medication used to treat nausea, vomiting, and gastroesophageal reflux disease (GERD) by increasing muscle contractions in the upper digestive tract.",
        usage: "Take metoclopramide tablets orally as directed, usually 30 minutes before meals and at bedtime.",
        side_effects: "Common side effects include drowsiness, restlessness, and headache.",
        precautions: "Do not take metoclopramide if you have a history of seizures or gastrointestinal bleeding.",
        categories: ["Gastrointestinal"],
    },
    {
        name: "Famotidine",
        description: "Famotidine is an H2 blocker medication used to treat heartburn, acid indigestion, and stomach ulcers by reducing the production of stomach acid.",
        usage: "Take famotidine tablets or capsules orally with water as directed, usually once or twice daily.",
        side_effects: "Side effects may include headache, constipation, and diarrhea.",
        precautions: "Do not take famotidine for more than 14 days for heartburn without consulting your doctor.",
        categories: ["Gastrointestinal"],
    },
    {
        name: "Psyllium",
        description: "Psyllium is a bulk-forming fiber supplement used to treat constipation, irritable bowel syndrome (IBS), and diarrhea by absorbing water and adding bulk to stool.",
        usage: "Mix psyllium powder or granules with a full glass of water or other liquid and drink immediately, followed by another glass of water.",
        side_effects: "Common side effects include gas, bloating, and cramping.",
        precautions: "Take psyllium with plenty of water to prevent choking or intestinal blockage.",
        categories: ["Gastrointestinal"],
    },

    // Hematology
    {
        name: "Iron Supplements",
        description: "Iron supplements are medications used to treat iron deficiency anemia by increasing the body's iron stores and improving red blood cell production.",
        usage: "Take iron supplements orally with water or as directed by your doctor, usually on an empty stomach.",
        side_effects: "Common side effects include constipation, nausea, and stomach pain.",
        precautions: "Take iron supplements with food if they cause stomach upset.",
        categories: ["Hematology"],
    },
    {
        name: "Folic Acid",
        description: "Folic acid is a B vitamin supplement used to treat and prevent folate deficiency anemia and to support fetal development during pregnancy.",
        usage: "Take folic acid tablets orally with water as directed by your doctor.",
        side_effects: "Side effects are rare but may include nausea, abdominal cramps, and allergic reactions.",
        precautions: "Tell your doctor if you are pregnant or breastfeeding before taking folic acid supplements.",
        categories: ["Hematology"],
    },
    {
        name: "Erythropoietin",
        description: "Erythropoietin is a hormone medication used to treat anemia associated with chronic kidney disease, chemotherapy, or HIV infection by stimulating red blood cell production in the bone marrow.",
        usage: "Erythropoietin is usually given as an injection under the skin or into a vein by a healthcare professional.",
        side_effects: "Common side effects include headache, nausea, and injection site reactions.",
        precautions: "Do not shake the erythropoietin vial or mix it with other medications or solutions.",
        categories: ["Hematology"],
    },
    {
        name: "Vitamin B12 Supplements",
        description: "Vitamin B12 supplements are medications used to treat and prevent vitamin B12 deficiency anemia by increasing the body's vitamin B12 levels.",
        usage: "Take vitamin B12 supplements orally with water as directed by your doctor.",
        side_effects: "Side effects are rare but may include diarrhea, itching, and blood clots.",
        precautions: "Tell your doctor if you have a history of allergic reactions to vitamin B12 or cobalt.",
        categories: ["Hematology"],
    },
    {
        name: "Eltrombopag",
        description: "Eltrombopag is a medication used to treat low platelet counts (thrombocytopenia) in people with chronic immune thrombocytopenia (ITP) or chronic hepatitis C virus infection.",
        usage: "Take eltrombopag tablets orally with water on an empty stomach, at least 1 hour before or 2 hours after eating.",
        side_effects: "Common side effects include headache, nausea, and diarrhea.",
        precautions: "Do not take eltrombopag if you have certain liver problems or a history of blood clots.",
        categories: ["Hematology"],
    },

    // Neurological
    {
        name: "Gabapentin",
        description: "Gabapentin is a medication used to treat seizures, neuropathic pain, and restless legs syndrome by affecting certain chemicals in the brain.",
        usage: "Take gabapentin capsules or tablets orally with water as directed by your doctor.",
        side_effects: "Common side effects include dizziness, drowsiness, and peripheral edema.",
        precautions: "Do not stop taking gabapentin suddenly without consulting your doctor.",
        categories: ["Neurological"],
    },
    {
        name: "Pregabalin",
        description: "Pregabalin is a medication used to treat neuropathic pain, fibromyalgia, and certain types of seizures by affecting certain chemicals in the brain.",
        usage: "Take pregabalin capsules or tablets orally with water as directed by your doctor.",
        side_effects: "Common side effects include dizziness, drowsiness, and weight gain.",
        precautions: "Tell your doctor if you have a history of drug or alcohol abuse before taking pregabalin.",
        categories: ["Neurological"],
    },
    {
        name: "Levetiracetam",
        description: "Levetiracetam is a medication used to treat seizures and epilepsy by affecting certain chemicals in the brain.",
        usage: "Take levetiracetam tablets or oral solution orally with water as directed by your doctor.",
        side_effects: "Common side effects include dizziness, drowsiness, and irritability.",
        precautions: "Do not stop taking levetiracetam suddenly without consulting your doctor.",
        categories: ["Neurological"],
    },
    {
        name: "Topiramate",
        description: "Topiramate is a medication used to treat seizures, migraine headaches, and certain psychiatric disorders by affecting certain chemicals in the brain.",
        usage: "Take topiramate tablets or capsules orally with water as directed by your doctor.",
        side_effects: "Common side effects include dizziness, drowsiness, and difficulty concentrating.",
        precautions: "Use effective birth control while taking topiramate, as it may cause birth defects.",
        categories: ["Neurological"],
    },
    {
        name: "Baclofen",
        description: "Baclofen is a muscle relaxant medication used to treat muscle spasms and spasticity associated with multiple sclerosis, spinal cord injuries, or other neurological conditions.",
        usage: "Take baclofen tablets orally with water as directed by your doctor.",
        side_effects: "Common side effects include drowsiness, weakness, and dizziness.",
        precautions: "Do not stop taking baclofen suddenly without consulting your doctor.",
        categories: ["Neurological"],
    },

    // Gynaecological
    {
        name: "Ethinyl Estradiol/Norethindrone",
        description: "Ethinyl estradiol/norethindrone is a combination hormonal contraceptive medication used to prevent pregnancy by stopping ovulation, thickening cervical mucus, and thinning the lining of the uterus.",
        usage: "Take ethinyl estradiol/norethindrone tablets orally with water as directed by your doctor.",
        side_effects: "Common side effects include nausea, headache, and breast tenderness.",
        precautions: "Tell your doctor if you have a history of blood clots, high blood pressure, or liver problems before taking ethinyl estradiol/norethindrone.",
        categories: ["Gynaecological"],
    },
    {
        name: "Levonorgestrel",
        description: "Levonorgestrel is a progestin-only emergency contraceptive medication used to prevent pregnancy after unprotected sex or contraceptive failure.",
        usage: "Take levonorgestrel tablets orally as soon as possible after unprotected sex, preferably within 72 hours.",
        side_effects: "Common side effects include nausea, abdominal pain, and fatigue.",
        precautions: "Do not use levonorgestrel as a regular form of birth control.",
        categories: ["Gynaecological"],
    },
    {
        name: "Mifepristone/Misoprostol",
        description: "Mifepristone/misoprostol is a combination medication used to terminate early pregnancy (up to 10 weeks gestation) by blocking the action of progesterone and inducing uterine contractions.",
        usage: "Take mifepristone orally as directed by your doctor, followed by misoprostol buccally (between the cheek and gum) or vaginally 24 to 48 hours later.",
        side_effects: "Common side effects include abdominal pain, cramping, and vaginal bleeding.",
        precautions: "This medication should only be used under the supervision of a healthcare provider trained in abortion procedures.",
        categories: ["Gynaecological"],
    },
    {
        name: "Clomiphene",
        description: "Clomiphene is a fertility medication used to induce ovulation in women who do not ovulate regularly or who have unexplained infertility.",
        usage: "Take clomiphene tablets orally with water as directed by your doctor, usually for 5 days starting on the fifth day of your menstrual cycle.",
        side_effects: "Common side effects include hot flashes, mood swings, and breast tenderness.",
        precautions: "Tell your doctor if you have a history of ovarian cysts or liver disease before taking clomiphene.",
        categories: ["Gynaecological"],
    },
    {
        name: "Estradiol",
        description: "Estradiol is a female hormone medication used to treat symptoms of menopause such as hot flashes, vaginal dryness, and night sweats.",
        usage: "Take estradiol tablets orally with water as directed by your doctor.",
        side_effects: "Common side effects include headache, breast pain, and nausea.",
        precautions: "Use the lowest effective dose of estradiol for the shortest duration necessary to control symptoms.",
        categories: ["Gynaecological"],
    },

    // Pulmonary
    {
        name: "Albuterol",
        description: "Albuterol is a bronchodilator medication used to treat asthma, chronic obstructive pulmonary disease (COPD), and other breathing problems by relaxing muscles in the airways and increasing airflow to the lungs.",
        usage: "Use albuterol inhalers or nebulizers as directed by your doctor, usually as needed for acute symptoms or on a regular schedule for maintenance therapy.",
        side_effects: "Common side effects include headache, nervousness, and tremor.",
        precautions: "Do not exceed the recommended dose or frequency of albuterol without consulting your doctor.",
        categories: ["Pulmonary"],
    },
    {
        name: "Ipratropium",
        description: "Ipratropium is an anticholinergic medication used to treat chronic obstructive pulmonary disease (COPD) and other breathing problems by relaxing muscles in the airways and reducing mucus production.",
        usage: "Use ipratropium inhalers or nebulizers as directed by your doctor, usually 3 to 4 times daily.",
        side_effects: "Common side effects include dry mouth, throat irritation, and cough.",
        precautions: "Rinse your mouth with water after using ipratropium inhalers to prevent dry mouth and throat irritation.",
        categories: ["Pulmonary"],
    },
    {
        name: "Budesonide/Formoterol",
        description: "Budesonide/formoterol is a combination medication used to treat asthma and chronic obstructive pulmonary disease (COPD) by reducing inflammation in the airways and relaxing muscles in the airways to improve breathing.",
        usage: "Use budesonide/formoterol inhalers as directed by your doctor, usually 1 to 2 inhalations twice daily.",
        side_effects: "Common side effects include headache, throat irritation, and upper respiratory tract infection.",
        precautions: "Do not use budesonide/formoterol for sudden asthma attacks or acute COPD exacerbations.",
        categories: ["Pulmonary"],
    },
    {
        name: "Montelukast",
        description: "Montelukast is a leukotriene receptor antagonist medication used to prevent asthma attacks and treat allergic rhinitis by blocking the action of leukotrienes, which contribute to inflammation and bronchoconstriction.",
        usage: "Take montelukast tablets orally with water as directed by your doctor, usually once daily in the evening.",
        side_effects: "Common side effects include headache, abdominal pain, and upper respiratory infection.",
        precautions: "Montelukast is not intended for the relief of acute asthma attacks.",
        categories: ["Pulmonary"],
    },
    {
        name: "Theophylline",
        description: "Theophylline is a bronchodilator medication used to treat asthma, chronic obstructive pulmonary disease (COPD), and other breathing problems by relaxing muscles in the airways and increasing airflow to the lungs.",
        usage: "Take theophylline tablets orally with water as directed by your doctor, usually once or twice daily.",
        side_effects: "Common side effects include nausea, headache, and insomnia.",
        precautions: "Do not exceed the recommended dose of theophylline without consulting your doctor.",
        categories: ["Pulmonary"],
    },

    // Rheumatologic
    {
        name: "Ibuprofen",
        description: "Ibuprofen is a nonsteroidal anti-inflammatory drug (NSAID) medication used to reduce pain, fever, and inflammation associated with conditions such as arthritis, menstrual cramps, and minor injuries.",
        usage: "Take ibuprofen tablets orally with water as directed by your doctor, usually every 4 to 6 hours as needed.",
        side_effects: "Common side effects include stomach upset, heartburn, and dizziness.",
        precautions: "Do not take ibuprofen if you have a history of stomach ulcers or bleeding disorders.",
        categories: ["Rheumatologic", "Pain Killers"],
    },
    {
        name: "Naproxen",
        description: "Naproxen is a nonsteroidal anti-inflammatory drug (NSAID) medication used to reduce pain, fever, and inflammation associated with conditions such as arthritis, menstrual cramps, and minor injuries.",
        usage: "Take naproxen tablets orally with water as directed by your doctor, usually every 8 to 12 hours as needed.",
        side_effects: "Common side effects include stomach upset, heartburn, and dizziness.",
        precautions: "Do not take naproxen if you have a history of stomach ulcers or kidney problems.",
        categories: ["Rheumatologic", "Pain Killers"],
    },
    {
        name: "Prednisone",
        description: "Prednisone is a corticosteroid medication used to reduce inflammation and suppress the immune system in conditions such as rheumatoid arthritis, lupus, and inflammatory bowel disease.",
        usage: "Take prednisone tablets orally with water as directed by your doctor, usually once daily in the morning.",
        side_effects: "Common side effects include weight gain, fluid retention, and mood changes.",
        precautions: "Do not stop taking prednisone suddenly without consulting your doctor.",
        categories: ["Rheumatologic"],
    },
    {
        name: "Methotrexate",
        description: "Methotrexate is a disease-modifying antirheumatic drug (DMARD) medication used to treat rheumatoid arthritis, psoriasis, and certain types of cancer by suppressing the immune system and reducing inflammation.",
        usage: "Take methotrexate tablets orally with water as directed by your doctor, usually once weekly.",
        side_effects: "Common side effects include nausea, vomiting, and hair loss.",
        precautions: "Use effective contraception while taking methotrexate, as it can cause birth defects.",
        categories: ["Rheumatologic"],
    },
    {
        name: "Hydroxychloroquine",
        description: "Hydroxychloroquine is an antimalarial and immunomodulatory medication used to treat rheumatoid arthritis, lupus, and other autoimmune diseases by suppressing the immune system and reducing inflammation.",
        usage: "Take hydroxychloroquine tablets orally with water as directed by your doctor.",
        side_effects: "Common side effects include nausea, diarrhea, and headache.",
        precautions: "Tell your doctor if you have a history of vision problems or heart disease before taking hydroxychloroquine.",
        categories: ["Rheumatologic"],
    },

    // Dental
    {
        name: "Fluoride Toothpaste",
        description: "Fluoride toothpaste is a dental hygiene product used to prevent tooth decay and cavities by strengthening tooth enamel and reducing acid erosion.",
        usage: "Brush teeth with fluoride toothpaste twice daily for at least 2 minutes each time, focusing on all tooth surfaces.",
        side_effects: "Side effects are rare but may include fluoride toxicity if swallowed in large amounts.",
        precautions: "Children under 6 years old should use fluoride toothpaste in a pea-sized amount to minimize the risk of swallowing.",
        categories: ["Dental"],
    },
    {
        name: "Dental Floss",
        description: "Dental floss is a dental hygiene product used to remove plaque and food debris from between teeth and along the gumline, where toothbrushes cannot reach.",
        usage: "Floss teeth daily using a piece of dental floss or flossing tool, gently sliding it between each tooth and along the gumline.",
        side_effects: "Side effects are rare but may include gum bleeding or irritation if flossed too aggressively.",
        precautions: "Use caution when flossing around dental work or orthodontic appliances to avoid damage.",
        categories: ["Dental"],
    },
    {
        name: "Mouthwash",
        description: "Mouthwash is a dental hygiene product used to freshen breath, reduce plaque buildup, and kill bacteria in the mouth.",
        usage: "Rinse mouth with mouthwash for 30 to 60 seconds, then spit it out. Do not swallow mouthwash.",
        side_effects: "Side effects are rare but may include dry mouth or allergic reactions to certain ingredients.",
        precautions: "Avoid using mouthwash immediately after brushing teeth, as it may rinse away the beneficial effects of fluoride toothpaste.",
        categories: ["Dental"],
    },
    {
        name: "Toothbrush",
        description: "A toothbrush is a dental hygiene tool used to remove plaque and food debris from teeth and gums, promoting oral health and preventing tooth decay and gum disease.",
        usage: "Brush teeth with a toothbrush twice daily for at least 2 minutes each time, using gentle circular motions and reaching all tooth surfaces.",
        side_effects: "Side effects are rare but may include gum irritation or enamel wear if brushed too aggressively.",
        precautions: "Replace toothbrush every 3 to 4 months or sooner if bristles become frayed or worn.",
        categories: ["Dental"],
    },
    {
        name: "Dental Sealants",
        description: "Dental sealants are a preventive dental treatment used to protect teeth from decay by sealing the grooves and fissures on the chewing surfaces of molars and premolars.",
        usage: "Dental sealants are applied by a dentist or dental hygienist in a quick and painless procedure.",
        side_effects: "Side effects are rare but may include allergic reactions to the sealant material.",
        precautions: "Dental sealants are most effective when applied to permanent molars shortly after they erupt.",
        categories: ["Dental"],
    },

    // Eye
    {
        name: "Artificial Tears",
        description: "Artificial tears are lubricating eye drops used to relieve dryness and discomfort associated with insufficient tear production or environmental factors such as wind, smoke, or prolonged screen time.",
        usage: "Instill artificial tears into the eyes as needed, usually 1 to 2 drops per eye, or as directed by your doctor.",
        side_effects: "Side effects are rare but may include temporary blurred vision or mild eye irritation.",
        precautions: "Avoid touching the tip of the artificial tears container to prevent contamination.",
        categories: ["Eye"],
    },
    {
        name: "Antihistamine Eye Drops",
        description: "Antihistamine eye drops are medications used to relieve itching, redness, and swelling caused by allergic conjunctivitis (eye allergies) by blocking the action of histamine in the eyes.",
        usage: "Instill antihistamine eye drops into the eyes as directed, usually 1 to 2 drops per eye, or as needed for symptom relief.",
        side_effects: "Side effects are rare but may include temporary burning or stinging upon instillation.",
        precautions: "Remove contact lenses before using antihistamine eye drops and wait at least 10 minutes before reinserting them.",
        categories: ["Eye"],
    },
    {
        name: "Cyclosporine Eye Drops",
        description: "Cyclosporine eye drops are immunosuppressive medications used to treat chronic dry eye disease (keratoconjunctivitis sicca) by reducing inflammation and promoting tear production.",
        usage: "Instill cyclosporine eye drops into the eyes as directed, usually 1 drop per eye twice daily, or as prescribed by your doctor.",
        side_effects: "Side effects may include burning, stinging, or temporary blurred vision upon instillation.",
        precautions: "Do not touch the tip of the cyclosporine eye drop container to prevent contamination.",
        categories: ["Eye"],
    },
    {
        name: "Lubricating Ointment",
        description: "Lubricating eye ointment is a thick, gel-like substance used to provide long-lasting relief from dryness and discomfort associated with severe dry eye syndrome, particularly at night.",
        usage: "Apply a small amount of lubricating eye ointment to the lower eyelid before bedtime, gently closing the eye to spread the ointment across the surface.",
        side_effects: "Side effects are rare but may include temporary blurred vision or mild eye irritation.",
        precautions: "Do not drive or engage in activities that require clear vision immediately after applying lubricating eye ointment.",
        categories: ["Eye"],
    },
    {
        name: "Prescription Eye Drops",
        description: "Prescription eye drops are medications used to treat various eye conditions such as glaucoma, infections, inflammation, and allergies.",
        usage: "Instill prescription eye drops into the eyes as directed by your doctor, following the specific instructions for your condition.",
        side_effects: "Side effects vary depending on the medication and may include burning, stinging, or temporary blurred vision.",
        precautions: "Follow your doctor's instructions carefully and report any persistent or severe side effects.",
        categories: ["Eye"],
    },
    {
    name: "Amoxicillin",
    description: "Amoxicillin is a common antibiotic used to treat bacterial infections such as respiratory infections, ear infections, and urinary tract infections by inhibiting the growth of bacteria.",
    usage: "Take amoxicillin capsules or tablets orally with water as directed by your doctor.",
    side_effects: "Common side effects include diarrhea, nausea, and rash.",
    precautions: "Tell your doctor if you have a history of allergic reactions to penicillin or other antibiotics before taking amoxicillin.",
    categories: ["Antibiotics"],
},
{
    name: "Azithromycin",
    description: "Azithromycin is an antibiotic used to treat bacterial infections such as respiratory infections, skin infections, and sexually transmitted diseases by inhibiting the growth of bacteria.",
    usage: "Take azithromycin tablets or oral suspension orally with water as directed by your doctor.",
    side_effects: "Common side effects include diarrhea, nausea, and abdominal pain.",
    precautions: "Tell your doctor if you have a history of liver or kidney disease before taking azithromycin.",
    categories: ["Antibiotics"],
},
{
    name: "Ciprofloxacin",
    description: "Ciprofloxacin is an antibiotic used to treat bacterial infections such as urinary tract infections, respiratory infections, and skin infections by inhibiting the growth of bacteria.",
    usage: "Take ciprofloxacin tablets or oral suspension orally with water as directed by your doctor.",
    side_effects: "Common side effects include nausea, diarrhea, and dizziness.",
    precautions: "Avoid taking ciprofloxacin with dairy products or antacids, as they may interfere with absorption.",
    categories: ["Antibiotics"],
},
{
    name: "Doxycycline",
    description: "Doxycycline is an antibiotic used to treat bacterial infections such as respiratory infections, skin infections, and sexually transmitted diseases by inhibiting the growth of bacteria.",
    usage: "Take doxycycline capsules or tablets orally with water as directed by your doctor.",
    side_effects: "Common side effects include nausea, vomiting, and diarrhea.",
    precautions: "Take doxycycline with plenty of water to reduce the risk of esophageal irritation and ulceration.",
    categories: ["Antibiotics"],
},
{
    name: "Clarithromycin",
    description: "Clarithromycin is an antibiotic used to treat bacterial infections such as respiratory infections, skin infections, and Helicobacter pylori infections by inhibiting the growth of bacteria.",
    usage: "Take clarithromycin tablets or oral suspension orally with water as directed by your doctor.",
    side_effects: "Common side effects include diarrhea, nausea, and abdominal pain.",
    precautions: "Tell your doctor if you have a history of liver or kidney disease before taking clarithromycin.",
    categories: ["Antibiotics"],
},
{
    name: "Paracetamol",
    description: "Paracetamol is a widely used analgesic (pain reliever) and antipyretic (fever reducer) medication. It is commonly used to alleviate mild to moderate pain and reduce fever.",
    usage: "Take paracetamol tablets orally with water as directed by your doctor or according to the instructions on the packaging.",
    side_effects: "Common side effects include nausea, vomiting, and allergic reactions such as skin rash.",
    precautions: "Do not exceed the recommended dosage of paracetamol to avoid liver damage. Consult your doctor if you have liver disease or consume alcohol regularly.",
    categories: ["Pain Killers"],
},

{
    name: "Ibuprofen",
    description: "Ibuprofen is a nonsteroidal anti-inflammatory drug (NSAID) and analgesic medication used to reduce pain, fever, and inflammation associated with conditions such as arthritis, menstrual cramps, and minor injuries.",
    usage: "Take ibuprofen tablets orally with water as directed by your doctor.",
    side_effects: "Common side effects include stomach upset, heartburn, and dizziness.",
    precautions: "Do not take ibuprofen if you have a history of stomach ulcers or bleeding disorders.",
    categories: ["Pain Killers"],
},
{
    name: "Acetaminophen",
    description: "Acetaminophen is an analgesic and antipyretic medication used to reduce pain and fever associated with conditions such as headaches, muscle aches, and colds.",
    usage: "Take acetaminophen tablets orally with water as directed by your doctor.",
    side_effects: "Common side effects include liver toxicity if taken in excessive doses.",
    precautions: "Do not exceed the recommended dose of acetaminophen to avoid liver damage.",
    categories: ["Pain Killers"],
},
{
    name: "Naproxen",
    description: "Naproxen is a nonsteroidal anti-inflammatory drug (NSAID) and analgesic medication used to reduce pain, fever, and inflammation associated with conditions such as arthritis, menstrual cramps, and minor injuries.",
    usage: "Take naproxen tablets orally with water as directed by your doctor.",
    side_effects: "Common side effects include stomach upset, heartburn, and dizziness.",
    precautions: "Do not take naproxen if you have a history of stomach ulcers or kidney problems.",
    categories: ["Pain Killers"],
},
{
    name: "Codeine",
    description: "Codeine is an opioid analgesic medication used to relieve mild to moderate pain and suppress coughing by binding to opioid receptors in the central nervous system.",
    usage: "Take codeine tablets orally with water as directed by your doctor.",
    side_effects: "Common side effects include drowsiness, constipation, and nausea.",
    precautions: "Do not drive or operate machinery while taking codeine, as it may cause drowsiness.",
    categories: ["Pain Killers"],
},

];


export const folderData = [
    { name: 'Antibiotics', image: require('../assets/antibiotics.jpg') },
    { name: 'Cardiovascular', image: require('../assets/Cardiologist-bro.png') },
    { name: 'Urology', image: require('../assets/urology.png') },
    { name: 'Dermatology', image: require('../assets/dermatology.png') },
    { name: 'ENT', image: require('../assets/head.png') },
    { name: 'Gastrointestinal', image: require('../assets/gastrointestinal-tract.png') },
    { name: 'Hematology', image: require('../assets/donator.png') },
    { name: 'Neurological', image: require('../assets/neurology.png') },
    { name: 'Gynaecological', image: require('../assets/maternity.png') },
    { name: 'Pulmonary', image: require('../assets/respiratory-system.png') },
  { name: 'Rheumatologic', image: require('../assets/Rheumatology-amico.png') },
    { name: 'Dental', image: require('../assets/tooth.png') },
    { name: 'Eye', image: require('../assets/eye.png') },
];

export default {med_wiki, folderData}